"""category name varchar 128->255, short_name 20->40

Revision ID: 2ded69877815
Revises: 4c8cfbd92ad8
Create Date: 2026-06-23 19:41:41.095250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ded69877815'
down_revision: Union[str, None] = '4c8cfbd92ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_org_usc'), table_name='buyer_organizations')
    op.drop_constraint(op.f('uq_buyer_org_usc'), 'buyer_organizations', type_='unique')
    op.create_index(op.f('ix_buyer_organizations_unified_social_credit_code'), 'buyer_organizations', ['unified_social_credit_code'], unique=True)
    op.alter_column('categories', 'name_zh',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'name_sw',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'short_name_zh',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('categories', 'short_name_en',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('categories', 'short_name_sw',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'product_count')
    op.drop_index(op.f('ix_products_source'), table_name='products')
    op.create_index('ix_rfq_quote_items_quote_id', 'rfq_quote_items', ['quote_id'], unique=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_rfq_quote_items_quote_id', table_name='rfq_quote_items')
    op.create_index(op.f('ix_products_source'), 'products', ['source'], unique=False)
    op.add_column('categories', sa.Column('product_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('categories', 'short_name_sw',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('categories', 'short_name_en',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('categories', 'short_name_zh',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('categories', 'name_sw',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('categories', 'name_en',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('categories', 'name_zh',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_index(op.f('ix_buyer_organizations_unified_social_credit_code'), table_name='buyer_organizations')
    op.create_unique_constraint(op.f('uq_buyer_org_usc'), 'buyer_organizations', ['unified_social_credit_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_buyer_org_usc'), 'buyer_organizations', ['unified_social_credit_code'], unique=False)
    # ### end Alembic commands ###
