"""feat(rfq): add cart and rfq tables v0.2 (8 tables, quote as independent entity)

Revision ID: 2e3ee5b1066c
Revises: 1c6db231a44b
Create Date: 2026-06-10 11:22:43.749819
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3ee5b1066c'
down_revision: Union[str, None] = '1c6db231a44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_org_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_org_id'], ['buyer_organizations.id'], name='fk_carts_buyer_org_id'),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name='fk_carts_buyer_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_org_id', 'buyer_user_id', name='uq_carts_buyer_org_user')
    )
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfq_no', sa.String(length=40), nullable=False),
    sa.Column('buyer_org_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operator_assignee_id', sa.Integer(), nullable=True),
    sa.Column('accepted_quote_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('requested_delivery_place', sa.String(length=120), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('target_currency', sa.String(length=3), nullable=True),
    sa.Column('required_certifications', sa.Text(), nullable=True),
    sa.Column('attachment_urls', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_org_id'], ['buyer_organizations.id'], name='fk_rfqs_buyer_org_id'),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name='fk_rfqs_buyer_user_id'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_rfqs_created_by_user_id'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_%(table_name)s_deleted_by'),
    sa.ForeignKeyConstraint(['operator_assignee_id'], ['users.id'], name='fk_rfqs_operator_assignee_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfqs_buyer_org_id', 'rfqs', ['buyer_org_id'], unique=False)
    op.create_index(op.f('ix_rfqs_deleted_at'), 'rfqs', ['deleted_at'], unique=False)
    op.create_index('ix_rfqs_status', 'rfqs', ['status'], unique=False)
    op.create_index('uq_rfqs_rfq_no_active', 'rfqs', ['rfq_no'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('rfq_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('quote_no', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('quote_status', sa.String(length=20), nullable=False),
    sa.Column('trade_term', sa.String(length=10), nullable=True),
    sa.Column('named_place', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('eta_days', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quoted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_%(table_name)s_deleted_by'),
    sa.ForeignKeyConstraint(['quoted_by_user_id'], ['users.id'], name='fk_rfq_quotes_quoted_by_user_id'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name='fk_rfq_quotes_rfq_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_quotes_deleted_at'), 'rfq_quotes', ['deleted_at'], unique=False)
    op.create_index('uq_rfq_quotes_quote_no_active', 'rfq_quotes', ['quote_no'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_rfq_quotes_rfq_active', 'rfq_quotes', ['rfq_id'], unique=True, postgresql_where="quote_status = 'ACTIVE'")
    # 循环 FK：rfqs.accepted_quote_id → rfq_quotes.id（需在 rfq_quotes 建表后添加）
    op.create_foreign_key(
        'fk_rfqs_accepted_quote_id', 'rfqs', 'rfq_quotes',
        ['accepted_quote_id'], ['id'],
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='fk_cart_items_cart_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name='fk_cart_items_sku_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'sku_id', name='uq_cart_items_cart_sku')
    )
    op.create_table('rfq_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('product_name_snapshot_zh', sa.String(length=200), nullable=True),
    sa.Column('product_name_snapshot_en', sa.String(length=200), nullable=True),
    sa.Column('sku_spec_snapshot_zh', sa.String(length=200), nullable=True),
    sa.Column('sku_spec_snapshot_en', sa.String(length=200), nullable=True),
    sa.Column('uom_snapshot', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('target_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_%(table_name)s_deleted_by'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], name='fk_rfq_items_rfq_id'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name='fk_rfq_items_sku_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_items_deleted_at'), 'rfq_items', ['deleted_at'], unique=False)
    op.create_index('uq_rfq_items_rfq_sku_active', 'rfq_items', ['rfq_id', 'sku_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('rfq_quote_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('rfq_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('moq', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('cbm_per_unit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_weight_per_unit', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_%(table_name)s_deleted_by'),
    sa.ForeignKeyConstraint(['quote_id'], ['rfq_quotes.id'], name='fk_rfq_quote_items_quote_id'),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], name='fk_rfq_quote_items_rfq_item_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'rfq_item_id', name='uq_rfq_quote_items_quote_rfq_item')
    )
    op.create_index(op.f('ix_rfq_quote_items_deleted_at'), 'rfq_quote_items', ['deleted_at'], unique=False)
    op.create_table('rfq_quote_item_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_org_id', sa.Integer(), nullable=True),
    sa.Column('supplier_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('freight_cost_alloc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('insurance_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('export_clearance_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('consolidation_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_%(table_name)s_deleted_by'),
    sa.ForeignKeyConstraint(['quote_item_id'], ['rfq_quote_items.id'], name='fk_rfq_quote_item_costs_quote_item_id'),
    sa.ForeignKeyConstraint(['supplier_org_id'], ['supplier_organizations.id'], name='fk_rfq_quote_item_costs_supplier_org_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_quote_item_costs_deleted_at'), 'rfq_quote_item_costs', ['deleted_at'], unique=False)
    op.create_index('uq_rfq_quote_item_costs_quote_item_active', 'rfq_quote_item_costs', ['quote_item_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('rfq_quote_item_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_item_id', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_item_id'], ['rfq_quote_items.id'], name='fk_rfq_quote_item_tiers_quote_item_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_item_id', 'min_qty', name='uq_rfq_quote_item_tiers_item_qty')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfq_quote_item_tiers')
    op.drop_index('uq_rfq_quote_item_costs_quote_item_active', table_name='rfq_quote_item_costs', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_rfq_quote_item_costs_deleted_at'), table_name='rfq_quote_item_costs')
    op.drop_table('rfq_quote_item_costs')
    op.drop_index(op.f('ix_rfq_quote_items_deleted_at'), table_name='rfq_quote_items')
    op.drop_table('rfq_quote_items')
    op.drop_index('uq_rfq_items_rfq_sku_active', table_name='rfq_items', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_rfq_items_deleted_at'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_table('cart_items')
    # 先删循环 FK 再删 rfq_quotes
    op.drop_constraint('fk_rfqs_accepted_quote_id', 'rfqs', type_='foreignkey')
    op.drop_index('uq_rfq_quotes_rfq_active', table_name='rfq_quotes', postgresql_where="quote_status = 'ACTIVE'")
    op.drop_index('uq_rfq_quotes_quote_no_active', table_name='rfq_quotes', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_rfq_quotes_deleted_at'), table_name='rfq_quotes')
    op.drop_table('rfq_quotes')
    op.drop_index('uq_rfqs_rfq_no_active', table_name='rfqs', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_rfqs_status', table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_deleted_at'), table_name='rfqs')
    op.drop_index('ix_rfqs_buyer_org_id', table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_table('carts')
    # ### end Alembic commands ###
