"""feat: registration optimization - add whatsapp, deactivated status, verification_codes table

Revision ID: 6b79e9ef98e2
Revises: f1a2b3c4d5e6
Create Date: 2026-06-29 18:28:19.309990
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b79e9ef98e2'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ref_price_tiers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('users', sa.Column('whatsapp', sa.String(length=30), nullable=True))
    op.alter_column('verification_codes', 'code_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('verification_codes', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('ix_vc_email_purpose', 'verification_codes', ['email', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vc_email_purpose', table_name='verification_codes')
    op.alter_column('verification_codes', 'user_agent',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verification_codes', 'code_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'whatsapp')
    op.alter_column('products', 'ref_price_tiers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
