"""create_product_catalog_tables

Revision ID: b826c151c8cc
Revises: 9e56690ae8cc
Create Date: 2026-06-04 20:15:31.167072
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b826c151c8cc'
down_revision: Union[str, None] = '9e56690ae8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attr_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=False),
    sa.Column('attr_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('attr_type', sa.String(length=20), nullable=False),
    sa.Column('attr_unit', sa.String(length=20), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], name='fk_attr_templates_category_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code', 'attr_key', name='uq_attr_templates_category_key')
    )
    op.create_index('ix_attr_templates_category_code', 'attr_templates', ['category_code'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('price_min', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_max', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], name='fk_products_category_code'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_products_created_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_index('ix_products_category_code', 'products', ['category_code'], unique=False)
    op.create_index('ix_products_is_featured', 'products', ['is_featured'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_table('product_attrs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attr_key', sa.String(length=50), nullable=False),
    sa.Column('attr_value', sa.String(length=200), nullable=False),
    sa.Column('attr_unit', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_attrs_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attr_key', name='uq_product_attrs_product_key')
    )
    op.create_index('ix_product_attrs_product_id', 'product_attrs', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_images_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_table('product_suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_org_id', sa.Integer(), nullable=False),
    sa.Column('supplier_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('supplier_moq', sa.Integer(), nullable=True),
    sa.Column('supplier_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('has_pvoc', sa.Boolean(), nullable=False),
    sa.Column('has_coc', sa.Boolean(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_suppliers_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_org_id'], ['supplier_organizations.id'], name='fk_product_suppliers_supplier_org_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'supplier_org_id', name='uq_product_suppliers_product_supplier')
    )
    op.create_index('ix_product_suppliers_product_id', 'product_suppliers', ['product_id'], unique=False)
    op.create_index('ix_product_suppliers_supplier_org_id', 'product_suppliers', ['supplier_org_id'], unique=False)
    op.add_column('categories', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('product_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'product_count')
    op.drop_column('categories', 'icon')
    op.drop_index('ix_product_suppliers_supplier_org_id', table_name='product_suppliers')
    op.drop_index('ix_product_suppliers_product_id', table_name='product_suppliers')
    op.drop_table('product_suppliers')
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_product_attrs_product_id', table_name='product_attrs')
    op.drop_table('product_attrs')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_is_featured', table_name='products')
    op.drop_index('ix_products_category_code', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_attr_templates_category_code', table_name='attr_templates')
    op.drop_table('attr_templates')
    # ### end Alembic commands ###
