"""报价单 PDF 三语标签。"""
from __future__ import annotations

LABELS: dict[str, dict[str, str]] = {
    "zh": {
        "doc_title": "报价单",
        "quote_no": "报价单号",
        "rfq_no": "询价单号",
        "issue_date": "签发日期",
        "valid_until": "有效期至",
        "from_title": "报价方",
        "to_title": "收件方",
        "contact": "联系人",
        "trade_terms": "交易条款",
        "trade_term": "贸易术语",
        "named_place": "指定地点",
        "currency": "币种",
        "delivery_place": "交货地",
        "destination_port": "目的港",
        "expected_delivery": "期望交期",
        "lead_time": "供货周期(天)",
        "eta": "预计到达(天)",
        "items_title": "报价明细",
        "col_no": "序号",
        "col_product": "商品名称",
        "col_variant": "规格",
        "col_qty": "数量",
        "col_unit": "单位",
        "col_unit_price": "单价",
        "col_amount": "小计",
        "col_remark": "备注",
        "tier_label": "阶梯价",
        "tier_min_qty": "起订量",
        "fee_section": "费用",
        "subtotal_products": "商品小计",
        "subtotal_fees": "费用小计",
        "total": "合计",
        "disclaimer": "本报价单为形式报价,不构成具有法律约束力的成交发票。最终价格及条款以双方签署的正式合同为准。",
        "generated_at": "生成时间",
    },
    "en": {
        "doc_title": "Quotation",
        "quote_no": "Quotation No.",
        "rfq_no": "RFQ No.",
        "issue_date": "Issue Date",
        "valid_until": "Valid Until",
        "from_title": "From",
        "to_title": "To",
        "contact": "Contact",
        "trade_terms": "Trade Terms",
        "trade_term": "Incoterms",
        "named_place": "Named Place",
        "currency": "Currency",
        "delivery_place": "Delivery Place",
        "destination_port": "Destination Port",
        "expected_delivery": "Expected Delivery",
        "lead_time": "Lead Time (days)",
        "eta": "ETA (days)",
        "items_title": "Quotation Details",
        "col_no": "#",
        "col_product": "Product",
        "col_variant": "Specification",
        "col_qty": "Qty",
        "col_unit": "Unit",
        "col_unit_price": "Unit Price",
        "col_amount": "Amount",
        "col_remark": "Remark",
        "tier_label": "Tiered Pricing",
        "tier_min_qty": "Min Qty",
        "fee_section": "Fees",
        "subtotal_products": "Subtotal (Products)",
        "subtotal_fees": "Subtotal (Fees)",
        "total": "Total",
        "disclaimer": "This quotation is a proforma document and does not constitute a legally binding invoice. Final pricing and terms are subject to a formally executed contract between the parties.",
        "generated_at": "Generated at",
    },
    "sw": {
        "doc_title": "Hati ya Nukuu",
        "quote_no": "Nambari ya Nukuu",
        "rfq_no": "Nambari ya RFQ",
        "issue_date": "Tarehe ya Kutolewa",
        "valid_until": "Inatumika Hadi",
        "from_title": "Kutoka",
        "to_title": "Kwa",
        "contact": "Mawasiliano",
        "trade_terms": "Masharti ya Biashara",
        "trade_term": "Incoterms",
        "named_place": "Mahali Palipotajwa",
        "currency": "Sarafu",
        "delivery_place": "Mahali pa Utoaji",
        "destination_port": "Bandari ya Marudio",
        "expected_delivery": "Utoaji Unaotarajiwa",
        "lead_time": "Muda wa Usambazaji (siku)",
        "eta": "ETA (siku)",
        "items_title": "Maelezo ya Nukuu",
        "col_no": "#",
        "col_product": "Bidhaa",
        "col_variant": "Vipimo",
        "col_qty": "Idadi",
        "col_unit": "Kipimo",
        "col_unit_price": "Bei ya Kipimo",
        "col_amount": "Jumla",
        "col_remark": "Maoni",
        "tier_label": "Bei za Ngazi",
        "tier_min_qty": "Kiwango cha Chini",
        "fee_section": "Ada",
        "subtotal_products": "Jumla Ndogo (Bidhaa)",
        "subtotal_fees": "Jumla Ndogo (Ada)",
        "total": "Jumla Kuu",
        "disclaimer": "Nukuu hii ni hati ya proforma na haiundi ankara yenye nguvu ya kisheria. Bei za mwisho na masharti yanategemea mkataba rasmi kati ya pande zote.",
        "generated_at": "Imetolewa saa",
    },
}


def get_labels(locale: str) -> dict[str, str]:
    """按 locale 返回标签字典,回退到英语。"""
    return LABELS.get(locale, LABELS["en"])
